# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 08:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WinRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.FloatField(help_text=b'Time taken to sweep all mines')),
                ('level', models.CharField(help_text=b'Level could be either Advanced or Nightmare', max_length=20)),
                ('user', models.ForeignKey(help_text=b'User to whom record is belogs', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
